SELECT * FROM ARTISTAS;

SELECT COUNT(*) AS TOTAL_ARTISTAS FROM ARTISTAS;

SELECT NOME, MUSICA_MAIS_OUVIDA FROM ARTISTAS;


SELECT NOME, MUSICA_MAIS_OUVIDA FROM ARTISTAS WHERE PAIS_ORIGEM = 'Reino Unido';

SELECT NOME, MUSICA_MAIS_OUVIDA FROM ARTISTAS WHERE id = 3;

