SELECT * FROM JOGADORES;

SELECT COUNT(*) AS TOTAL_JOGADORES FROM JOGADORES;

SELECT GOLS, NOME FROM JOGADORES;


SELECT GOLS, NOME FROM JOGADORES WHERE PAIS_ORIGEM = 'Brasil';

SELECT GOLS, NOME FROM JOGADORES WHERE id = 3;

