CREATE TABLE ARTISTAS (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(200) NOT NULL,
    TIPO VARCHAR(25) NOT NULL,
    MEMBROS INTEGER,
    GENERO_MUSICAL VARCHAR(50),
    PAIS_ORIGEM VARCHAR(50),
    ANO_INICIO INTEGER,
    MUSICA_MAIS_OUVIDA VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE
);

